
- name: Install ziti CLI
  hosts: all
  become: true
  gather_facts: true  # facts used by repo role to detect distribution family
  roles:
    - community.openziti.openziti_repo
  tasks:
    - name: Install ziti CLI
      ansible.builtin.package:
        name: openziti
        state: present